
<div class="container">
    <div class="row">
        <div class="col order-2 order-md-1 order-sm-2">
            <form method="post" action="/add">
                <div class="form-group row">
                    <label for="inputName" class="col-lg-2 col-form-label">Название</label>
                    <div class="col-lg-10">
                        <input type="text" name="name" class="form-control" id="inputName">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputCoutry" class="col-lg-2 col-form-label">Цена</label>
                    <div class="col-lg-10">
                        <input type="text" name="price" class="form-control" id="inputPrice">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputCoutry" class="col-lg-2 col-form-label">Страна</label>
                    <div class="col-lg-10">
                        <input type="text" name="country" class="form-control" id="inputCoutry">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputManufacturer" class="col-lg-2 col-form-label">Производитель</label>
                    <div class="col-lg-10">
                        <input type="text" name="manufacturer" class="form-control" id="inputManufacturer">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputExpiresAt" class="col-lg-2 col-form-label">Годен до</label>
                    <div class="col-lg-10">
                        <input type="date" name="expires_at" class="form-control" id="inputExpiresAt">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputDescription" class="col-lg-2 col-form-label">Описание</label>

                    <div class="col-lg-10">
                        <textarea  name="description" id ="inputDescription" class="form-control inputstl" rows="5"></textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="offset-lg-2 col-lg-10">
                        <button type="submit" class="btn btn-lg btn-block btn-primary">Добавить</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3 sidebar order-1 order-md-2 order-sm-1">
            <div class="list-group">
                <a href="/" class="list-group-item list-group-item-action">
                    Показать все товары
                </a>
                <a href="#" class="list-group-item list-group-item-secondary">Добавить</a>
                <a href="/search" class="list-group-item list-group-item-action">Найти</a>
            </div>
        </div>
    </div>
</div>